"""Tests for GHIN per-hole score extraction — offline, no network.

ghin_hole_scores.csv is generated by build_hole_scores() in pull_ghin.py.
Verifies: correct row count (18 per round with hole_details), hole_number/par/
raw_score present, null fields tolerated, dedupe across recent/revision buckets.
"""
import json
import os

import pull_ghin


FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")


def _load_fixture(name: str):
    with open(os.path.join(FIXTURES, name), encoding="utf-8") as f:
        return json.load(f)


def test_hole_score_row_count():
    """score-001 has 18 hole_details; score-002 has null hole_details -> 0 rows."""
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    # score-001 appears in both recent_scores and revision_scores — must dedupe to 18 rows
    assert len(rows) == 18


def test_hole_number_and_par_present():
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    hole_numbers = {r["hole_number"] for r in rows}
    assert hole_numbers == set(range(1, 19))
    # Par 4 holes dominate; par 3 and 5 also present
    pars = {r["par"] for r in rows}
    assert 3 in pars and 4 in pars and 5 in pars


def test_raw_score_present():
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    for r in rows:
        assert r["raw_score"] is not None


def test_null_fields_tolerated():
    """Many per-hole stats are null (drive_accuracy, approach_shot_accuracy, etc.)."""
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    # drive_accuracy is null in fixture for all holes
    assert all(r["drive_accuracy"] is None for r in rows)


def test_dedupe_across_recent_and_revision():
    """score-001 in both recent_scores and revision_scores yields only 18 rows (not 19)."""
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    score_ids = {r["score_id"] for r in rows}
    assert score_ids == {"score-001"}
    assert len(rows) == 18


def test_score_with_null_hole_details_produces_no_rows():
    """score-002 has hole_details=null; should produce zero rows for that score."""
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    rows_s2 = [r for r in rows if r["score_id"] == "score-002"]
    assert rows_s2 == []


def test_played_at_and_course_name_from_parent():
    scores = _load_fixture("ghin_scores.json")
    rows = pull_ghin.build_hole_scores(scores)
    for r in rows:
        assert r["played_at"] == "2026-06-08"
        assert r["course_name"] == "WindRose Golf Club"


def test_empty_dict_returns_empty():
    assert pull_ghin.build_hole_scores({}) == []


def test_none_returns_empty():
    assert pull_ghin.build_hole_scores(None) == []


def test_hole_score_cols_defined():
    assert "score_id" in pull_ghin.HOLE_SCORE_COLS
    assert "hole_number" in pull_ghin.HOLE_SCORE_COLS
    assert "par" in pull_ghin.HOLE_SCORE_COLS
    assert "raw_score" in pull_ghin.HOLE_SCORE_COLS
    assert "putts" in pull_ghin.HOLE_SCORE_COLS
    assert "gir_flag" in pull_ghin.HOLE_SCORE_COLS


def test_multi_round_inline():
    """Two rounds each with hole_details — total rows = sum of hole counts."""
    two_rounds = {
        "recent_scores": {
            "scores": [
                {
                    "id": "r1",
                    "played_at": "2026-06-01",
                    "course_name": "Course A",
                    "hole_details": [
                        {"hole_number": i, "par": 4, "raw_score": 5} for i in range(1, 10)
                    ],
                },
                {
                    "id": "r2",
                    "played_at": "2026-05-25",
                    "course_name": "Course B",
                    "hole_details": [
                        {"hole_number": i, "par": 4, "raw_score": 6} for i in range(1, 19)
                    ],
                },
            ]
        }
    }
    rows = pull_ghin.build_hole_scores(two_rounds)
    assert len(rows) == 9 + 18
    # Sorted newest first
    assert rows[0]["played_at"] == "2026-06-01"
